### ISSUE TITLE
So Exciting!

### ISSUE THREAD

**Issue by andyedison** [thda/tds#1]
Greetings, I discovered this library from the Golang Weekly email newsletter. I am SO excited to see more drivers supporting Sybase (SAP) databases. I do a lot of work on ASE, and have fallen in love with go the last couple years, but it has always been tough to use go with Sybase products.

I've been using the gofreetds package by minus5 https://github.com/minus5/gofreetds, but it's major limitation for my team is that it that particular implementation requires the linux freetds installed on the system, whereas almost my whole team are Windows users.

I have a fork of that repo here https://github.com/andyedison/gofreetds with a couple small tweaks that let Sybase be used as the database/sql package. 

Anyways, please let me know how I could help in making this package production ready!

**Comment by thda** [comment]
Hi,

thanks for the kind words !
Can you please run the tests, try this database with as many dev instances as possible ?

This driver almost fully supports database/sql (no named parameters is the only flaw I know), along with context-based timeouts which gofreetds does not support.

It will production ready after fuzzing (github.com/dvyukov/go-fuzz) is implemented for each datatype, I need to make sure charset conversion works fine, and that the data you put in is the same as the one you put out.

Right now I'm just using it to monitor some instances, so it's not using a variety of data types.

Please let me know when you have a chance to test !

**Comment by andyedison** [comment]
Sure thing. I'll work on getting a test instance up and running that I can kick the tires with. 

Will let you know for sure!

**Comment by thda** [comment]
Also, please use master, as the row count is not properly handled in v0.1.2.

**Comment by andyedison** [comment]
Ok will do

**Comment by andyedison** [comment]
Hi, here are the results from initial test. This is a sybase instance running inside a docker container (https://hub.docker.com/r/datagrip/sybase) but I have tested it being able to connect from AquaData Studio via localhost:5000.

Testing output
```
==> TDS_USERNAME=sa TDS_PASSWORD=myPassword TDS_SERVER=localhost:5000 go test
--- FAIL: TestColumnTypeIntrospection (0.08s)
    stmt_test.go:1100: Query failed with unexpected error tds: loginAck receive failed: netlib: unexpected EOF while reading message
--- FAIL: TestColumnIntrospection (0.00s)
    driver_test.go:76: sql.Ping failed: tds: loginAck receive failed: netlib: unexpected EOF while reading message
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1116997]

goroutine 1554 [running]:
testing.tRunner.func1(0xc00030a100)
        /usr/local/opt/go/libexec/src/testing/testing.go:792 +0x387
panic(0x12abb40, 0x15b31c0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:513 +0x1b9
database/sql.(*DB).Close(0x0, 0x10c70cd, 0xc00037a7d0)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:759 +0x37
panic(0x12abb40, 0x15b31c0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:513 +0x1b9
database/sql.(*DB).conn(0x0, 0x1359140, 0xc000088008, 0x1, 0x15, 0x39, 0x15)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:1081 +0x3a
database/sql.(*DB).query(0x0, 0x1359140, 0xc000088008, 0xc0004bb9e0, 0x60, 0x0, 0x0, 0x0, 0x1, 0x12ecca0, ...)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:1514 +0x66
database/sql.(*DB).QueryContext(0x0, 0x1359140, 0xc000088008, 0xc0004bb9e0, 0x60, 0x0, 0x0, 0x0, 0x60, 0xc0004bb9e0, ...)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:1496 +0xd3
database/sql.(*DB).Query(0x0, 0xc0004bb9e0, 0x60, 0x0, 0x0, 0x0, 0x60, 0xc0004cc7e0, 0xc00037a7d0)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:1510 +0x82
github.com/thda/tds.TestColumnIntrospection(0xc00030a100)
        /Users/aedison/Projects/go/src/github.com/thda/tds/stmt_test.go:1162 +0x2a9
testing.tRunner(0xc00030a100, 0x1317610)
        /usr/local/opt/go/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /usr/local/opt/go/libexec/src/testing/testing.go:878 +0x35c
exit status 2
FAIL    github.com/thda/tds     2.548s
```



```
[root@1df48341c5ff /]# isql -Usa -SMYSYBASE
Password:
1> select @@version
2> go

 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Adaptive Server Enterprise/16.0 SP02 PL02/EBF 25320 SMP/P/x86_64/Enterprise Lin
         ux/ase160sp02plx/2492/64-bit/FBO/Sat Nov 21 04:05:39 2015

(1 row affected)
```

**Comment by thda** [comment]
Hi,

I could reproduce, I think, using your docker image.

The bug was in the tests which were not calling rows.Close(), thus leaking connections.
As this docker image is a dev edition, the number of user connections is limited.

I've also tried my best to avoid retuning nil, returning bad connection or empty result sets instead.

This should make it less likely for the caller to get nil pointer when an error is not properly checked.

Can you please try ?

**Comment by andyedison** [comment]
Sure thing, I'll try out master again. 

I'll check out gsql, and I was poking around usql the other day after finding this repo. Very neat stuff.

Yes the connection limit on Developer Edition ASE is VERY frustrating. A lot of things SAP/Sybase do are very frustrating, but that's a topic for another day :-)

**Comment by thda** [comment]
Great news ! Thanks for reporting

**Comment by andyedison** [comment]
Thanks again for this package! If there is anything you need help with, be it documentation, tests, bug testing, whatever, I'd be happy to help out.

**Comment by thda** [comment]
Well testing, transferring data is all that's needed. I'm closing this one. If you need help, my email is on my profile. Cheers.

**Comment by andyedison** [comment]
Did want to add one last thing, in case you were unaware, but I was able to get this to build successfully on a windows 10 machine. Huge deal for my team.
