### ISSUE TITLE
float value is not insert db 

### ISSUE THREAD

**Issue by abxd39** [thda/tds#12]
https://github.com/thda/tds/blob/cf9b6a04cd036b574225616e8251e14ab4868f55/num.go#L129
what TODO？ @thda

**Comment by zxy82005337** [comment]
my code like this 
db.Exec("insert into LC_BATCHTRANS(BATCHID,AMOUNT,STATUS,FAMEBCUSNO,SUBMITTIME,SUBMITTLR,TRANSTYPE,ABS) values ?,?,?,?,?,?,?,?)", "test001", "0.01", "N", "002", time.Now(), "002", "0", "test")
but when the value of AMOUNT is less than 1,such as 0.01 or 0.10,the sql before can't take effect

**Comment by thda** [comment]
Hi,
Is your amount field a float or a numeric?
Can you give me the table's ddl?

**Comment by zxy82005337** [comment]
> Hi,
> Is your amount field a float or a numeric?
> Can you give me the table's ddl?

decimal

**Comment by zxy82005337** [comment]
> decimal
it has nothing to do with the type of field, when the sql is working,it will be stopped by the code in the 129 rows of num.go

**Comment by thda** [comment]
Indeed but I need the type of field to reproduce.

**Comment by zxy82005337** [comment]
the error info:
/usr/local/go/src/runtime/panic.go:35 (0x42afbd)
	panicslice: panic(sliceError)
/var/www_edu_plugins/bank-api/src/sctek.com/edu-plugins/bank-api/vendor/github.com/thda/tds/num.go:129 (0xaadf4b)
	Num.String: return string(b[:len(b)-2-int(n.scale)]) + "." + string(b[len(b)-2-int(n.scale):len(b)-2])
/var/www_edu_plugins/bank-api/src/sctek.com/edu-plugins/bank-api/vendor/github.com/thda/tds/num.go:186 (0xaae3e7)
	numConverter.ConvertValue: return []byte(num.String()), err
/usr/local/go/src/database/sql/convert.go:83 (0x968fac)
	ccChecker.CheckNamedValue: nv.Value, err = c.cci.ColumnConverter(index).ConvertValue(arg)
/usr/local/go/src/database/sql/convert.go:171 (0x97cb6b)
	(ccChecker).CheckNamedValue-fm: checker = cc.CheckNamedValue
/usr/local/go/src/database/sql/convert.go:171 (0x97cb6b)
	(ccChecker).CheckNamedValue-fm: checker = cc.CheckNamedValue
/usr/local/go/src/database/sql/convert.go:175 (0x9694b3)
	driverArgsConnLocked: err = checker(nv)
/usr/local/go/src/database/sql/sql.go:2260 (0x977c8f)
	resultFromStatement: dargs, err := driverArgsConnLocked(ci, ds, args)
/usr/local/go/src/database/sql/sql.go:1410 (0x97392b)
	(*DB).execDC: return resultFromStatement(ctx, dc.ci, ds, args...)
/usr/local/go/src/database/sql/sql.go:1371 (0x973620)
	(*DB).exec: return db.execDC(ctx, dc, dc.releaseConn, query, args)
/usr/local/go/src/database/sql/sql.go:1349 (0x973230)
	(*DB).ExecContext: res, err = db.exec(ctx, query, args, cachedOrNewConn)
/usr/local/go/src/database/sql/sql.go:1363 (0x9734a4)
	(*DB).Exec: return db.ExecContext(context.Background(), query, args...)

**Comment by zxy82005337** [comment]
> Indeed but I need the type of field to reproduce.

the type of AMOUNT is  DECIMAL (15,2)

**Comment by thda** [comment]
Thanks for the input. I should be able to provide a fix tomorrow. Will keep you updated

**Comment by thda** [comment]
I could reproduce.
I'll push an update tomorrow.

**Comment by thda** [comment]
Can you please test against Master?
