### ISSUE TITLE
Does this work with sybase 16 ?

### ISSUE THREAD

**Issue by jaijiv** [thda/tds#13]
Hi,

I was doing a quick check of this driver against our sybase ase 16. I encountered a hang on db.Ping then timedout. Before i dig deeper, was wondering if this works against 16?

Thanks

-jaijiv

**Comment by thda** [comment]
Hi,

I run all my tests on ASE 16 SP02.

Regards

**Comment by jaijiv** [comment]
we run ASE 16 SP03. It worked when i passed encryptPassword=no in connection string.

**Comment by thda** [comment]
Thanks, for the information. I'll check against an sp03.

**Comment by jaijiv** [comment]
What i found was encryptPassword was defaulting to try. In driver.Login code then password was going in empty and Login just hung and timedout after default of 20 seconds. Am assuming try implies trying with encryption, if not fallback to plain text.

**Comment by thda** [comment]
I'll try to add debug flags as I need to know what packet was blocking.  
Do you have the error message?

**Comment by jaijiv** [comment]
2019/12/29 19:00:52 Ping : netlib: Timeout reached, yet the cancel was not acknowledged

**Comment by jaijiv** [comment]
Hi Thomas,

Thanks for your work on this driver! I am evaluating this to replace our odbc based cgo driver. Any idea when this could be out of beta?

Regards

-jaijiv

**Comment by thda** [comment]
Hi,

I did a recent modification on numeric handling and need to add more test cases and use it myself a little more.

I'll try to reproduce and fix you issue with 16SP2.
Btw, what charset are you using? It might help me to reproduce.

Once those two topics are closed, I'll release a V1.

Cheers,
Thomas

**Comment by jaijiv** [comment]
utf8 charset

btw - i updated to your latest which fixed issues with some numerics on large data sets. Pretty cool! thanks! Are you in touch with sybase team ? - it seems they are trying to build a pure go driver

**Comment by thda** [comment]
Hi,

I have installed sp3 servers in utf8 charset. I'll try to reproduce your password encryption issue. 
I'm in touch with the sap team and asked them for some documentation a while back. 
As of now I have no visibility on their road map, so I suggest you contact them.

Cheers

**Comment by thda** [comment]
Hi again,

I've reproduced your issue and found a fix.
I should cut a release during this week.

Cheers

**Comment by jaijiv** [comment]
that is great! thanks

**Comment by jaijiv** [comment]
hi - wondering if will be doing this soon? Thanks!

**Comment by thda** [comment]
Hi,

I didn't get time to push the fix, I'm still testing things. Will try to release this month.

**Comment by thda** [comment]
I've pushed a fix in the master branch. Could you please let me know if it works for you

**Comment by bgould** [comment]
@thda thank you for this fix! Some of our servers were upgraded over the weekend to SP02 PL09 from PL05 and we encountered this exact issue.  I've tested with the master branch and it seems 100% solved to me.  Thank you!

**Comment by thda** [comment]
Thanks for checking on your side. I will close the issue. @jaijiv, could you please reopen if it's not fixed ?
