### ISSUE TITLE
cannot connect to Sybase ASE 12.5.4 with charset=cp850 

### ISSUE THREAD

**Issue by slam-coder** [thda/tds#15]
I'm trying to use this project to connect to a Sybase ASE 12.5.4 database.
cnxStr := "tds://sa:@192.168.211.128:5000/test?charset=cp850"
But it didn't work,the error is blow. Do you have any pointers? Thanks
 tds: cannot encode to 'cp850' charset

**Comment by thda** [comment]
Hi,

I'll check. Could you please let me know the character set of your instance ?

Thanks

**Comment by slam-coder** [comment]
The character set for my instance is CP850

**Comment by thda** [comment]
Hi,

it should be fixed in master.

Could you please check ?

Thanks

**Comment by thda** [comment]
Closing due to age. Should be fixed in master
