### ISSUE TITLE
Seems like prepared statements are not working.

### ISSUE THREAD

**Issue by tenenwurcel** [thda/tds#18]
I am trying to use a prepared statement to run in my Sybase, with the following code:

```go
cnxStr := "tds://xxxxx:xxxxxxx@xxxx.xxxxxxxxx.xx.xx:2638/xxxx?charset=utf8"
db, err := sql.Open("tds", cnxStr)

fmt.Println("OK1")

if err != nil {
	fmt.Println(err)
}

fmt.Println("OK2")

rows, err := db.Query("SELECT nome_cta, codi_cta FROM bethadba.ctcontas WHERE codi_cta = ?", 1)
fmt.Println("OK3")
```

When I run this, it get stuck on the db.Query, it never prints out "OK3".

But if I run the same query:

```go
db.Query("SELECT nome_cta, codi_cta FROM bethadba.ctcontas WHERE codi_cta = 1")
```

It runs perfectly.

I can't give you a lot of details, because it also doesn't return me an error.

Sybase version : 16.0.0.2754

Thank you so much for the help !

**Comment by thda** [comment]
Hi,

thanks for reporting. Is it possible to give me the output of "sp_help" on the table ?

Thanks

**Comment by thda** [comment]
Closing due to age
