### ISSUE TITLE
Export Driver

### ISSUE THREAD

**Issue by nvx** [thda/tds#21]
Most SQL driver packages either export the driver struct directly, or export an instance of the driver struct. Note that database/sql package does not provide a way to obtain a driver.Driver for a given driver name outside of the sql package itself.

This is useful as it allows packages like instrumentedsql to wrap a driver to add instrumentation. For example https://github.com/luna-duclos/instrumentedsql/blob/f5ba2826f7af02db3068b0261754cb828a704237/examples/sql_example_test.go#L20 leverages the exported sqlite3.SQLiteDriver struct to create a new driver instance to wrap. This same pattern is used by the postgres driver pq where the struct is pq.Driver, go-mssqldb where the struct is mssqldb.Driver, and mysql as mysql.MySQLDriver. Oddly the go-oci8 library takes the approach of exporting an instance of the driver at oci8.Driver rather than the struct, but this still works fine as long as a sql driver.Driver can be obtained.

I'm not sure which of the two options is the most idiomatic, but more do seem to opt for exporting the struct itself rather than exporting an instance of the driver.

**Comment by thda** [comment]
Hi,

I would do what mysql and postgresql drivers do.
I'll change the needed letter and push it to master.

**Comment by thda** [comment]
I've exported SybaseDriver (in the master branch). Can you please let me know if it's ok for you?

**Comment by nvx** [comment]
Looks good to me, cheers!
