### ISSUE TITLE
Can't specify a dbname

### ISSUE THREAD

**Issue by yohan212** [thda/tds#24]
Hello everyone, 
First of all thank's for your work ! 
This is my issue:

```
package main

import (
	"database/sql"
	_ "flag"
	"fmt"
	"os"

	_ "github.com/thda/tds"
)

func main() {
	db, err := sql.Open("tds", "tds://username:password@IP:2638/dbnameA?charset=utf8")
	if err != nil {
		fmt.Printf("Failed to open database: %v", err)
		os.Exit(1)
	}
	defer db.Close()
	err = db.Ping()
	if err != nil {
		fmt.Printf("Failed to ping database: %v", err)
		os.Exit(1)
	}
	fmt.Println("ok")
	var result string
	row, _ := db.Query("select db_name()")
	for row.Next() {
		row.Scan(&result)
	}
	fmt.Println(result)
	os.Exit(0)

}
```
Response : 
`ok
defaultDB`

If I specify a db name into the connection string I can do "select x from TableOfDbA" but if I do "select db_name()" the response will be DefaultDB.
If I specify a Db into the connection string, and if this DB doesn't exist, I don't have an error message because a connection is made with the default db. This is a problem because I use this script to monitor all db on the server.
Thank's for your help

**Comment by thda** [comment]
Thanks for reporting.

Could you please give me the name of the software you are using (ASE, IQ, Replication server), and the exact version of you server ?

**Comment by yohan212** [comment]
Hello Thank's for your reply
My Product: Sql Anywhere 16
My Version: 16.0.0.2283

**Comment by thda** [comment]
I do not have access to SQL Anywhere unfortunately. Can you please confirm it's not an IQ server ?

**Comment by thda** [comment]
closing due to age.
SQL anywhere is not supported by this driver
