### ISSUE TITLE
Driver always try connecting to Default Database even if i specify DatabaseName

### ISSUE THREAD

**Issue by RohitBinjola** [thda/tds#25]
First of all thanks for writing this driver that has solved alot for me, below is the issue that i am facing with this driver.

Issue:- Our Database server has 3 databases in it with default database as DBAs database that they use for maintainence, Now when i try to connect to my database, Driver always tries to connect to default Database even if i specify database name in connection string and as a result i always get error saying "Invalid UserName or Password" since my Database username and password do not works with default database.

We are using SQL Anywhere 17.0

Can this be looked upon please.

My Code is below:

```
package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/url"
	"time"
	_ "github.com/thda/tds"
)

func main1() {
	Init()
}

func buildCnxStr() string {
	return "tds://" + url.QueryEscape("<UserName>") + ":" + url.QueryEscape("<Password>") +
		"@" + url.QueryEscape("<HostName>") + ":" + "<DatabaseName>" + "/" + "<DatabaseName>" + "?" + "charset=utf8"
}

func Init() {
	dbConntString := buildCnxStr()
	db, err := sql.Open("tds", dbConntString)
	db.SetMaxOpenConns(4)
	db.SetMaxIdleConns(1)
	db.SetConnMaxLifetime(60 * time.Second)
	if err != nil {
		log.Fatal(err)
	}

	var result string
	row, err := db.Query("select db_name()") // Here i am getting error
	if err != nil {
		fmt.Println("Error is: ", err)
	}
	for row.Next() {
		row.Scan(&result)
	}

	fmt.Println("Database Name is: ", result)
}
```

**Comment by thda** [comment]
Unfortunately SQL anywhere is not supported by this driver.
Thus I am closing.
I'd gladly accept PRs adding support though.
