### ISSUE TITLE
issue with dependency

### ISSUE THREAD

**Issue by barum** [thda/tds#5]
Hi!

trying to get the code working and running into this issue.

```
go: finding github.com/thda/tablewriter v0.0.0-20180207080603-aedbbc0800df
Username for 'https://github.com': 
```

We can do a `go get github.com/thda/tds` without any issues.

But when trying to use inside the project and doing `go mod tidy`, we get that prompt.

Is there is a dependency on the  private repo above?

thank!

**Comment by thda** [comment]
Thanks for reporting. I'll fix this within two days. 
I've removed the dependancy to this library so it should not try to resolve it.

**Comment by thda** [comment]
Could you please update to v0.1.5 and tell me if it fixes your issue?

**Comment by barum** [comment]
Fixed! thank you for quick response! Great work!
